exports.routesConfig = {
  baseURL: '/api',
  app: {
    path: '/app',
    versions: {
      v1: {
        path: '/v1',
        routes: {
          fileHandler: {
            path: '/fileHandler',
            subPaths: {
              uploadSingleFile: '/upload-single-file',
              uploadMultipleFiles: '/upload-multiple-files',
              deleteSingleFile: '/delete-single-file',
              deleteMultipleFiles: '/delete-multiple-files', 
            },
          },
          employee: {
            path: '/employee',
            subPaths: {
              root: '/',
              create: '/create',
              update: '/update',
              getAllEmployees: '/get-all-employees',
              getEmployeeById: '/get-employee-by-id',
              delete: '/delete',
              getEmployeeExpenses: '/get-employee-expenses',
            },
          },
          attendance: {
            path: '/attendance',
            subPaths: {
              root: '/',
              markAttendanceOfAllEmployees: '/mark-attendance',
              updateAttendanceOfAllEmployees: '/update-attendance',
              getOneDayAttendanceOfAllEmployees: '/get-one-day-attendance',
              getAttendanceDetailOfOneEmployee: '/get-employee-attendance-detail',
              getAttendanceById: '/get-attendance-by-id',
              getFullMonthAttendanceOfOneEmployee: '/get-monthly-attendance',
              getFullMonthAttendanceOfAllEmployee: '/get-monthly-attendance-all',
              deleteAttendance: '/delete-attendance-by-id',
            },
          },
          salary: {
            path: '/salary',
            subPaths: {
              root: '/',
              generateSalaryOfAllEmployees: '/generate-salary',
              getSalaryHistoryOfAllEmployees: '/salary-history',
              getSalaryHistoryOfAnEmployee: '/employee-salary-history',
              getSalaryDetail: '/salary-detail',
              updateSalary: '/update-salary',
              updateSalaryStatus: '/update-salary-status',
              processLoanDeductions: '/process-loan-deductions',
            },
          },
          loan: {
            path: '/loan',
            subPaths: {
              root: '/',
              createLoan: '/create',
              getAllLoans: '/get-all-loans',
              getLoanById: '/get-loan-by-id',
              getEmployeeLoans: '/get-employee-loans',
              updateLoanStatus: '/update-status',
              payInstallment: '/pay-installment',
              updateLoan: '/update',
              deleteLoan: '/delete',
            },
          },
          customer: {
            path: '/customer',
            subPaths: {
              root: '/',
              createCustomer: '/create',
              getAllCustomers: '/get-all-customers',
              getCustomerById: '/get-customer-by-id',
              getCustomersByContractor: '/get-customers-by-contractor',
              updateCustomer: '/update',
              updateCustomerStatus: '/update-status',
              deleteCustomer: '/delete',
              searchCustomers: '/search',
              getCustomerStats: '/stats',
            },
          },
          contractor: {
            path: '/contractor',
            subPaths: {
              root: '/',
              createContractor: '/create',
              getAllContractors: '/get-all-contractors',
              getContractorById: '/get-contractor-by-id',
              updateContractor: '/update',
              deleteContractor: '/delete',
              searchContractors: '/search',
              getContractorStats: '/stats',
            },
          },
          vendor: {
            path: '/vendor',
            subPaths: {
              root: '/',
              createVendor: '/create',
              getAllVendors: '/get-all-vendors',
              getVendorById: '/get-vendor-by-id',
              updateVendor: '/update',
              deleteVendor: '/delete',
            },
          },
          vendorOrder: {
            path: '/vendor-order',
            subPaths: {
              root: '/',
              createVendorOrder: '/create',
              getAllVendorOrders: '/get-all-vendor-orders',
              getVendorOrderById: '/get-vendor-order-by-id',
              getVendorOrdersByVendor: '/get-vendor-orders-by-vendor',
              updateVendorOrder: '/update',
              updateVendorOrderStatus: '/update-status',
              approveVendorOrder: '/approve',
              deleteVendorOrder: '/delete',
              searchVendorOrders: '/search',
              getVendorOrderStats: '/stats',
            },
          },
          director: {
            path: '/director',
            subPaths: {
              root: '/',
              createDirector: '/create',
              getAllDirectors: '/get-all-directors',
              getDirectorById: '/get-director-by-id',
              updateDirector: '/update',
              deleteDirector: '/delete',
            },
          },
          dailyEntry: {
            path: '/daily-entry',
            subPaths: {
              root: '/',
              createEntry: '/create',
              getAllEntries: '/get-all-entries',
              getEntryById: '/get-entry-by-id',
              updateEntry: '/update',
              deleteEntry: '/delete',
              saveTodayEntries: '/save-today-entries',
              getEntriesByDateOrBetweenDates: '/get-entries-by-date',
            },
          },
          quotation: {
            path: '/quotation',
            subPaths: {
              root: '/',
              createQuotation: '/create',
              getAllQuotations: '/get-all-quotations',
              getQuotationById: '/get-quotation-by-id',
              getQuotationsByCustomer: '/get-quotations-by-customer',
              updateQuotation: '/update',
              updateQuotationStatus: '/update-status',
              deleteQuotation: '/delete',
              searchQuotations: '/search',
              getQuotationStats: '/stats',
              convertToInvoice: '/convert-to-invoice',
            },
          },
          invoice: {
            path: '/invoice',
            subPaths: {
              root: '/',
              createInvoice: '/create',
              getAllInvoices: '/get-all-invoices',
              getInvoiceById: '/get-invoice-by-id',
              getInvoicesByCustomer: '/get-invoices-by-customer',
              updateInvoice: '/update',
              updateInvoiceStatus: '/update-status',
              deleteInvoice: '/delete',
              searchInvoices: '/search',
              getInvoiceStats: '/stats',
              createLedgerEntry: '/create-ledger-entry',
              sendInvoice: '/send',
            },
          },
          ledger: {
            path: '/ledger',
            subPaths: {
              root: '/',
              createLedger: '/create',
              getAllLedger: '/get-all-ledger',
              getLedgerById: '/get-ledger-by-id',
              getLedgerByType: '/get-ledger-by-type',
              addTransaction: '/add-transaction',
              addInvoiceTransaction: '/add-invoice-transaction',
              addVendorOrderTransaction: '/add-vendor-order-transaction',
              updateLedger: '/update',
              deleteLedger: '/delete',
            },
          },
          profile: {
            path: '/profile',
            subPaths: {
              root: '/',
              updateProfile: '/update-profile',
              updateCompany: '/update-company',
            },
          },
          till: {
            path: '/till',
            subPaths: {
              root: '/',
              initializeTill: '/initialize',
              getTill: '/get',
              updateTill: '/update',
              deleteTill: '/delete',
            },
          },
          reports: {
            path: '/reports',
            subPaths: {
              docxToPdfConvert: '/docx-to-pdf',
              expenseReport: '/expense-report',
              getTotalEmployeeVendorCustomer: '/total-counts',
              getMonthlySalaryReport: '/monthly-salary',
              getRemainingBalanceReport: '/remaining-balance',
            },
          },
        },
      },
    },
  },
  auth: {
    path: '/auth',
    versions: {
      v1: {
        path: '/v1',
        routes: {
          user: {
            path: '/user',
            subPaths: {
              root: '/',
              signIn: '/signin',
              signUp: '/signup',
            },
          },
        },
      },
    },
  },
  methods: {
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    DELETE: 'DELETE',
  },
};
